NAME_MAP_TO_NAME_DATA = {
    'Bosnia and Herz.': 'Bosnia and Herzegovina',
    'Brunei': 'Brunei Darussalam',
    'Central African Rep.': 'Central African Republic',
    'Czechia': 'Czech Republic',
    'Dem. Rep. Congo': 'Congo, The Democratic Republic',
    'Dominican Rep.': 'Dominican Republic',
    'Gambia': 'Gambia, The',
    'Kosovo': 'Kosovar',
    'Libya': 'Libya(Libyan Arab Jamahir)',
    'N. Cyprus': 'Cyprus',
    'North Macedonia': 'Macedonia',
    'Palestine': 'Palestinian Territories',
    'Russia': 'Russian Federation',
    'S. Sudan': 'South Sudan',
    'Slovakia': 'Slovakia(Slovak Republic)',
    'Solomon Is.': 'Solomon Islands',
    'South Africa': 'South Africa-Zuid Afrika',
    'South Korea': 'South Korea ',
    'Syria': 'Syrian Arab Republic',
    'Taiwan': 'Taiwan Province of China',
    'United States of America': 'United States',
    'Vietnam': 'Viet Nam',
    'Yemen': 'Yemen (Yemen Arab Republic)',
    'Zambia': 'Zambia(Northern Rhodesia)',
    'eSwatini': 'Swaziland',
}
